insert into public.roadmap_days (day_number, title, description, learning_objectives, estimated_time)
values
(1,'Introduction to Python','Learn what Python is, where it is used, how to write your first Python program, and understand print statements.',array['Understand Python basics','Learn print()','Learn comments','Write first Python program'],'30 minutes'),
(2,'Variables and Data Types','Store values in variables and recognize common Python data types like strings, integers, floats, and booleans.',array['Create variables','Inspect data types','Use meaningful names','Update stored values'],'40 minutes'),
(3,'Operators','Use arithmetic, comparison, logical, and assignment operators to build expressions.',array['Use arithmetic operators','Compare values','Combine conditions','Practice assignment operators'],'40 minutes'),
(4,'Input and Output','Read user input, format output, and convert text input into useful data types.',array['Use input()','Convert strings to numbers','Format output','Build interactive scripts'],'45 minutes'),
(5,'Conditional Statements','Make decisions with if, elif, and else blocks.',array['Write conditions','Use if statements','Handle multiple branches','Apply nested checks'],'45 minutes'),
(6,'Loops','Repeat work with for loops and while loops.',array['Use for loops','Use while loops','Control loops with break','Build repeated tasks'],'50 minutes'),
(7,'String Basics','Work with text using indexing, slicing, methods, and formatting.',array['Index strings','Slice text','Use common methods','Format strings'],'45 minutes'),
(8,'Lists','Store ordered collections and modify them with list operations.',array['Create lists','Add and remove items','Loop through lists','Use list methods'],'50 minutes'),
(9,'Tuples and Sets','Use immutable tuples and unique-value sets for common collection tasks.',array['Create tuples','Unpack values','Create sets','Use set operations'],'45 minutes'),
(10,'Dictionaries','Represent key-value data with dictionaries.',array['Create dictionaries','Read and update values','Loop over key-value pairs','Use dictionary methods'],'50 minutes'),
(11,'Functions','Define reusable blocks of code with functions.',array['Define functions','Call functions','Use docstrings','Organize code'],'50 minutes'),
(12,'Function Parameters and Return Values','Pass data into functions and return calculated results.',array['Use parameters','Return values','Understand scope','Write reusable helpers'],'55 minutes'),
(13,'Lambda Functions','Create small anonymous functions and use them with simple transformations.',array['Write lambda expressions','Use map-like patterns','Sort with key functions','Know when not to use lambda'],'40 minutes'),
(14,'File Handling','Open, read, and write text files safely.',array['Read files','Write files','Use with blocks','Handle file paths'],'55 minutes'),
(15,'Exception Handling','Use try, except, else, and finally to handle errors gracefully.',array['Catch exceptions','Handle invalid input','Use finally','Avoid broad errors'],'50 minutes'),
(16,'Modules and Packages','Import built-in modules and organize code into files.',array['Import modules','Use aliases','Read module docs','Create simple modules'],'45 minutes'),
(17,'Date and Time','Work with dates, times, timedeltas, and formatted date strings.',array['Use datetime','Format dates','Calculate durations','Parse date strings'],'45 minutes'),
(18,'List Comprehension','Create lists concisely with comprehensions.',array['Write list comprehensions','Add conditions','Transform values','Compare with loops'],'45 minutes'),
(19,'OOP Introduction','Understand objects, classes, attributes, and methods at a beginner level.',array['Explain OOP terms','Identify objects','Model simple entities','Use methods'],'45 minutes'),
(20,'Classes and Objects','Define classes and create objects with attributes and behavior.',array['Create classes','Instantiate objects','Use self','Add methods'],'55 minutes'),
(21,'Constructors','Initialize objects with __init__ and default attribute values.',array['Use __init__','Pass constructor values','Set defaults','Create multiple objects'],'50 minutes'),
(22,'Inheritance','Share behavior between parent and child classes.',array['Create child classes','Reuse parent methods','Override methods','Recognize inheritance use cases'],'55 minutes'),
(23,'Encapsulation','Group data with behavior and use naming conventions for internal state.',array['Understand encapsulation','Use properties','Protect object state','Write clear interfaces'],'50 minutes'),
(24,'Polymorphism','Use common method names across different object types.',array['Understand polymorphism','Call shared methods','Use duck typing','Design flexible functions'],'45 minutes'),
(25,'Working with JSON','Read, write, and transform JSON data with Python dictionaries and lists.',array['Use json.loads','Use json.dumps','Access nested data','Format JSON output'],'50 minutes'),
(26,'Basic Python Projects','Combine fundamentals into small scripts.',array['Plan small scripts','Combine loops and functions','Use collections','Improve output'],'60 minutes'),
(27,'Debugging Basics','Find and fix bugs using prints, tracebacks, and small test cases.',array['Read tracebacks','Use print debugging','Isolate bugs','Check assumptions'],'45 minutes'),
(28,'Practice Problems','Solve mixed beginner problems across strings, loops, lists, and functions.',array['Practice problem solving','Choose data structures','Write clear code','Test edge cases'],'60 minutes'),
(29,'Mini Project','Build a small command-line style Python project in the browser.',array['Break work into steps','Use functions','Store data','Polish output'],'75 minutes'),
(30,'Final Revision and Assessment','Review the full roadmap and complete a final set of beginner exercises.',array['Review core syntax','Solve assessment tasks','Reflect on weak areas','Plan next steps'],'60 minutes')
on conflict (day_number) do update
set title = excluded.title,
    description = excluded.description,
    learning_objectives = excluded.learning_objectives,
    estimated_time = excluded.estimated_time;

delete from public.exercises;

insert into public.exercises (day_id, title, problem_statement, starter_code, expected_output, difficulty, hints)
select d.id, e.title, e.problem, e.code, e.expected, e.difficulty, e.hints
from public.roadmap_days d
join (
  values
  (1,'Print Your Name','Write a Python program to print your name using the print() function.','print("")','Your name should be displayed in the output panel.','Easy',array['Put your name inside quotes.','Use print("Your Name").']),
  (1,'Two Line Greeting','Print Hello on one line and Python learner on the next line.','print("Hello")','Two separate lines should appear.','Easy',array['Use two print() statements.','Each print() creates a new line.']),
  (1,'Comment and Print','Add a comment above a print statement that prints I am learning Python.','# write a comment here','I am learning Python','Easy',array['Python comments start with #.','Comments do not appear in output.']),
  (2,'Create Variables','Create name and age variables, then print them.','name = ""\nage = 0\nprint(name)\nprint(age)','The name and age should print on separate lines.','Easy',array['Use quotes for text.','Numbers do not need quotes.']),
  (2,'Type Check','Create three variables and print their types.','city = "Delhi"\ntemperature = 28.5\nis_sunny = True\n','The output should include str, float, and bool types.','Easy',array['Use type(value).','Print each type.']),
  (2,'Update Score','Start score at 10, add 5, and print the final score.','score = 10\n# update score here\nprint(score)','15','Easy',array['Use score = score + 5.','The same variable can be reassigned.']),
  (3,'Basic Calculator','Print the sum, difference, product, and division of two numbers.','a = 12\nb = 4\n','16, 8, 48, and 3.0 should appear.','Easy',array['Use +, -, *, and /.','Print one result per line.']),
  (3,'Compare Ages','Print True if age is 18 or above.','age = 20\n','True','Easy',array['Use >=.','Print the comparison directly.']),
  (3,'Logical Check','Print True if a number is between 1 and 10 inclusive.','number = 7\n','True','Easy',array['Use and.','Check both lower and upper limits.']),
  (4,'Name Greeting','Ask for a name and print a greeting.','name = input("Enter name: ")\n','Hello followed by the entered name.','Easy',array['Use print("Hello", name).','input() always returns text.']),
  (4,'Add Two Numbers','Read two numbers, convert them to integers, and print their sum.','a = input("First: ")\nb = input("Second: ")\n','The numeric sum should print.','Easy',array['Use int().','Convert before adding.']),
  (4,'Formatted Sentence','Create item and price variables and print a clear sentence.','item = "book"\nprice = 120\n','The book costs 120','Easy',array['Use an f-string.','Put variables inside braces.']),
  (5,'Pass or Retry','Print Pass if marks are 50 or more, otherwise print Retry.','marks = 72\n','Pass','Easy',array['Use if and else.','Indent the print statements.']),
  (5,'Positive Negative Zero','Check whether a number is positive, negative, or zero.','number = -3\n','negative','Easy',array['Use if, elif, else.','Compare with 0.']),
  (5,'Even or Odd','Print Even or Odd for a number.','number = 8\n','Even','Easy',array['Use modulo %.','Even numbers have remainder 0 when divided by 2.']),
  (6,'Count to Five','Use a loop to print numbers from 1 to 5.','# write loop here','1 through 5 on separate lines.','Easy',array['Use range(1, 6).','Print the loop variable.']),
  (6,'Sum Numbers','Use a loop to calculate the sum of 1 to 10.','total = 0\n','55','Easy',array['Add each number to total.','Print after the loop.']),
  (6,'While Countdown','Use while to print 3, 2, 1, Go.','count = 3\n','3 2 1 Go on separate lines.','Easy',array['Decrease count each loop.','Print Go after the loop.']),
  (7,'String Length','Print the length of a word.','word = "python"\n','6','Easy',array['Use len().','Pass the string variable to len.']),
  (7,'First and Last','Print the first and last character of a string.','text = "roadmap"\n','r and p should appear.','Easy',array['Index 0 is first.','Index -1 is last.']),
  (7,'Uppercase Text','Convert a sentence to uppercase and print it.','sentence = "python is fun"\n','PYTHON IS FUN','Easy',array['Use .upper().','String methods return a new value.']),
  (8,'List Basics','Create a list of three fruits and print the second fruit.','fruits = ["apple", "banana", "mango"]\n','banana','Easy',array['List indexes start at 0.','Second item has index 1.']),
  (8,'Add to List','Append a city to a list and print the full list.','cities = ["Delhi", "Mumbai"]\n','The output should include Bengaluru.','Easy',array['Use append().','Print the list after appending.']),
  (8,'List Total','Find the total of numbers in a list.','numbers = [2, 4, 6, 8]\n','20','Easy',array['Use sum().','Or loop and add values.']),
  (9,'Tuple Unpack','Unpack a tuple into name and age, then print both.','person = ("Asha", 21)\n','Asha and 21 should print.','Easy',array['Use name, age = person.','Print both variables.']),
  (9,'Unique Numbers','Convert a list with duplicates into a set and print it.','numbers = [1, 2, 2, 3, 3, 3]\n','The output should contain 1, 2, and 3 once.','Easy',array['Use set(numbers).','Set order may vary.']),
  (9,'Set Intersection','Print common items from two sets.','a = {"python", "sql", "html"}\nb = {"python", "css"}\n','python','Easy',array['Use & or .intersection().','Print the result.']),
  (10,'Dictionary Lookup','Create a student dictionary and print the grade.','student = {"name": "Ravi", "grade": "A"}\n','A','Easy',array['Use student["grade"].','Keys are strings here.']),
  (10,'Update Dictionary','Update a product price and print the dictionary.','product = {"name": "pen", "price": 10}\n','The price should be 12.','Easy',array['Assign product["price"] = 12.','Print after updating.']),
  (10,'Loop Dictionary','Loop through a dictionary and print each key and value.','scores = {"math": 90, "science": 85}\n','Both subjects and scores should appear.','Easy',array['Use .items().','Print key and value inside the loop.']),
  (11,'Simple Function','Define a function that prints Welcome to Python.','def welcome():\n    pass\n\nwelcome()','Welcome to Python','Easy',array['Replace pass with print().','Call the function after defining it.']),
  (11,'Function Reuse','Define greet(name) and call it twice with different names.','def greet(name):\n    pass\n','Two greetings should appear.','Easy',array['Use a parameter.','Call greet("Asha") and greet("Ravi").']),
  (11,'Area Function','Write a function that prints area of a rectangle.','def area(length, width):\n    pass\n\narea(5, 3)','15','Easy',array['Multiply length and width.','Print the result.']),
  (12,'Return Square','Create a function that returns the square of a number.','def square(number):\n    pass\n\nprint(square(4))','16','Easy',array['Use return, not print, inside the function.','number * number gives square.']),
  (12,'Default Greeting','Create a greeting function with a default name.','def greet(name="learner"):\n    pass\n\nprint(greet())','Hello learner','Easy',array['Return an f-string.','Default parameters go in the definition.']),
  (12,'Total With Return','Return the sum of numbers in a list.','def total(numbers):\n    pass\n\nprint(total([1, 2, 3]))','6','Easy',array['Use sum(numbers).','Return the value.']),
  (13,'Lambda Double','Create a lambda that doubles a number.','double = lambda x: x\nprint(double(6))','12','Easy',array['Change x to x * 2.','Lambda returns the expression automatically.']),
  (13,'Sort by Length','Sort words by their length.','words = ["sun", "elephant", "book"]\n','sun, book, elephant order should appear.','Medium',array['Use sorted(words, key=lambda word: len(word)).','Print the sorted list.']),
  (13,'Filter Scores','Use a lambda with filter to keep scores 50 and above.','scores = [30, 55, 80, 42]\n','55 and 80 should remain.','Medium',array['Use filter(lambda score: score >= 50, scores).','Convert filter result to list.']),
  (14,'Read Text','Use a multi-line string as file-like content and print each line.','content = "one\\ntwo\\nthree"\n','one two three on separate lines.','Easy',array['Use splitlines().','Loop through each line.']),
  (14,'Write Lines','Create a list of lines and join them with newline characters.','lines = ["Python", "Files"]\n','Python and Files on separate lines.','Easy',array['Use "\\n".join(lines).','Print the joined text.']),
  (14,'Count Words','Count words in a text string.','text = "Python file handling is useful"\n','5','Easy',array['Use split().','Use len() on the list.']),
  (15,'Safe Division','Use try/except to handle division by zero.','a = 10\nb = 0\n','Show a friendly error message.','Easy',array['Put division inside try.','Catch ZeroDivisionError.']),
  (15,'Convert Input Safely','Convert a text value to int and handle invalid data.','value = "abc"\n','Show invalid number message.','Easy',array['Catch ValueError.','Use int(value) inside try.']),
  (15,'Finally Message','Use finally to print Done after a try block.','try:\n    print("Working")\nfinally:\n    pass','Working and Done should appear.','Easy',array['Replace pass with print("Done").','finally always runs.']),
  (16,'Math Module','Import math and print the square root of 81.','','9.0','Easy',array['Use import math.','Call math.sqrt(81).']),
  (16,'Random Choice','Import random and print one item from a list.','items = ["red", "blue", "green"]\n','One color should print.','Easy',array['Use random.choice(items).','Import random first.']),
  (16,'Alias Import','Import datetime with an alias and print today.','','Current date should print.','Easy',array['Use import datetime as dt.','Call dt.date.today().']),
  (17,'Today Date','Print today''s date using datetime.','','The current date should print.','Easy',array['from datetime import date.','Use date.today().']),
  (17,'Days Difference','Calculate days between two dates.','from datetime import date\nstart = date(2026, 1, 1)\nend = date(2026, 1, 10)\n','9','Easy',array['Subtract dates.','Use .days on the result.']),
  (17,'Format Date','Format a date as DD-MM-YYYY.','from datetime import date\nd = date(2026, 5, 26)\n','26-05-2026','Easy',array['Use strftime().','Format string is "%d-%m-%Y".']),
  (18,'Squares List','Use a list comprehension to create squares from 1 to 5.','','[1, 4, 9, 16, 25]','Easy',array['Use range(1, 6).','Expression is n * n.']),
  (18,'Even Numbers','Use a comprehension to keep even numbers from 1 to 10.','','[2, 4, 6, 8, 10]','Easy',array['Use if n % 2 == 0.','Put the condition at the end.']),
  (18,'Upper Names','Convert a list of names to uppercase with a comprehension.','names = ["asha", "ravi"]\n','ASHA and RAVI should appear in a list.','Easy',array['Use name.upper().','Loop through names inside brackets.']),
  (19,'Object Idea','Create a dictionary representing a book and print its title.','book = {"title": "Python Basics", "pages": 120}\n','Python Basics','Easy',array['Objects group related data.','Access the title key.']),
  (19,'Method Thinking','Create a function that accepts a user dictionary and returns a greeting.','user = {"name": "Asha"}\n','Hello Asha','Easy',array['Pass the dictionary into a function.','Read user["name"].']),
  (19,'Model a Product','Create product data and print a formatted label.','product = {"name": "Notebook", "price": 50}\n','Notebook: 50','Easy',array['Use an f-string.','Access both dictionary values.']),
  (20,'Create Class','Create a Student class and instantiate it.','class Student:\n    pass\n\nstudent = Student()\nprint(type(student).__name__)','Student','Easy',array['Class names use PascalCase.','The empty class can use pass.']),
  (20,'Add Attribute','Create an object and add a name attribute.','class Student:\n    pass\n\nstudent = Student()\n','A name should print.','Easy',array['Use student.name = "Asha".','Then print student.name.']),
  (20,'Add Method','Create a class method that prints a greeting.','class Greeter:\n    def say_hello(self):\n        pass\n\nGreeter().say_hello()','Hello','Easy',array['Methods need self.','Replace pass with print("Hello").']),
  (21,'Constructor Name','Use __init__ to store a name and print it.','class Student:\n    def __init__(self, name):\n        pass\n\nstudent = Student("Asha")\n','Asha','Easy',array['Assign self.name = name.','Print student.name.']),
  (21,'Default Level','Create a Course class with default level Beginner.','class Course:\n    def __init__(self, title):\n        self.title = title\n','Beginner','Easy',array['Set self.level = "Beginner".','Print course.level.']),
  (21,'Multiple Objects','Create two objects with different names and print both.','class Pet:\n    def __init__(self, name):\n        self.name = name\n','Two pet names should print.','Easy',array['Instantiate Pet twice.','Print each .name.']),
  (22,'Parent Method','Create a parent class Animal with speak method and call it from a child object.','class Animal:\n    def speak(self):\n        print("sound")\n\nclass Dog(Animal):\n    pass\n','sound','Easy',array['Dog inherits Animal.','Create Dog() and call speak().']),
  (22,'Override Method','Override speak in Dog to print bark.','class Animal:\n    def speak(self):\n        print("sound")\n\nclass Dog(Animal):\n    pass\n','bark','Easy',array['Define speak in Dog.','Child method replaces parent method.']),
  (22,'Use Super','Call a parent constructor using super().','class Person:\n    def __init__(self, name):\n        self.name = name\n\nclass Student(Person):\n    def __init__(self, name, grade):\n        pass\n','Name and grade should print.','Medium',array['Use super().__init__(name).','Set self.grade = grade.']),
  (23,'Private Convention','Create a BankAccount with _balance and a deposit method.','class BankAccount:\n    def __init__(self):\n        self._balance = 0\n','Balance should become 100.','Medium',array['Add deposit(self, amount).','Increase self._balance.']),
  (23,'Getter Method','Create a method that returns internal balance.','class Wallet:\n    def __init__(self):\n        self._amount = 50\n','50','Easy',array['Define get_amount(self).','Return self._amount.']),
  (23,'Validate Age','Only update age if the value is positive.','age = -5\n','Show valid age or invalid age message.','Easy',array['Use an if check.','Reject values below 0.']),
  (24,'Shared Method Name','Create two classes with describe methods and call both in a loop.','','Both descriptions should print.','Medium',array['Use same method name in each class.','Loop through object instances.']),
  (24,'Duck Typing','Write a function that calls .area() on any shape object.','','Area values should print.','Medium',array['Create classes with area methods.','Function only needs shape.area().']),
  (24,'Polymorphic Sounds','Create Cat and Dog classes with speak methods.','','meow and bark should print.','Easy',array['Use a list of objects.','Call speak on each object.']),
  (25,'JSON Loads','Convert a JSON string to a dictionary and print name.','import json\ndata = ''{"name": "Asha", "age": 21}''\n','Asha','Easy',array['Use json.loads(data).','Access ["name"].']),
  (25,'JSON Dumps','Convert a dictionary to formatted JSON text.','import json\nuser = {"name": "Ravi", "active": True}\n','JSON text should print.','Easy',array['Use json.dumps(user, indent=2).','Print the result.']),
  (25,'Nested JSON','Print the city from nested JSON-like data.','data = {"user": {"address": {"city": "Pune"}}}\n','Pune','Easy',array['Use chained keys.','data["user"]["address"]["city"].']),
  (26,'Tip Calculator','Calculate a 10 percent tip and total bill.','bill = 500\n','Tip 50 and total 550 should appear.','Easy',array['tip = bill * 0.10.','total = bill + tip.']),
  (26,'To Do List','Create a list of tasks, add one task, and print numbered tasks.','tasks = ["learn loops", "practice lists"]\n','Numbered task list should print.','Medium',array['Use append().','Use enumerate starting at 1.']),
  (26,'Quiz Score','Store answers and count correct ones.','answers = ["a", "b", "c"]\ncorrect = ["a", "c", "c"]\n','2','Medium',array['Loop over pairs with zip().','Increase score for matches.']),
  (27,'Fix NameError','Fix the code so it prints Python.','language = "Python"\nprint(langauge)','Python','Easy',array['Read the variable name carefully.','Both spellings must match.']),
  (27,'Fix Indentation','Fix indentation so the condition works.','score = 80\nif score > 50:\nprint("Pass")','Pass','Easy',array['Indented blocks are required.','Indent print by four spaces.']),
  (27,'Trace Values','Print intermediate values while calculating total.','prices = [10, 20, 30]\ntotal = 0\n','Total should end as 60.','Easy',array['Print total inside the loop.','Then print final total.']),
  (28,'Reverse String','Print a reversed string.','text = "python"\n','nohtyp','Easy',array['Use slicing.','[::-1] reverses a sequence.']),
  (28,'Largest Number','Find the largest number in a list.','numbers = [4, 9, 2, 11, 6]\n','11','Easy',array['Use max().','Or loop and compare.']),
  (28,'Count Vowels','Count vowels in a word.','word = "education"\n','5','Medium',array['Create a string of vowels.','Loop through letters and count matches.']),
  (29,'Contact Book','Create a small contact dictionary and print a selected phone number.','contacts = {"Asha": "111", "Ravi": "222"}\n','111','Easy',array['Access contacts["Asha"].','Print the value.']),
  (29,'Mini Menu','Create a simple menu list and print each option with a number.','options = ["Add", "View", "Exit"]\n','Numbered menu should print.','Easy',array['Use enumerate(options, start=1).','Format number and option.']),
  (29,'Project Summary','Create a function that returns a summary for tasks completed.','tasks_done = 3\ntotal_tasks = 5\n','3 of 5 tasks completed','Medium',array['Use a function with two parameters.','Return an f-string.']),
  (30,'Final Basics','Print a sentence using variables for name and days completed.','name = "Learner"\ndays = 30\n','Learner completed 30 days','Easy',array['Use an f-string.','Print one sentence.']),
  (30,'Final Function','Write a function that returns whether a number is even.','def is_even(number):\n    pass\n\nprint(is_even(10))','True','Easy',array['Return number % 2 == 0.','Boolean expressions can be returned directly.']),
  (30,'Final Challenge','Given numbers, print the squares of even numbers only.','numbers = [1, 2, 3, 4, 5, 6]\n','[4, 16, 36]','Medium',array['Use a comprehension.','Filter with n % 2 == 0 and transform with n * n.'])
) as e(day_number, title, problem, code, expected, difficulty, hints)
on d.day_number = e.day_number;
